name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
#       fail-fast: false
      matrix:
        config:
          - { os: windows-latest, cache: 'sccache', shell_prepare: '$env:MSYS2_ROOT="$home\scoop\apps\msys2\current"; $env:PATH="$env:MSYS2_ROOT\usr\bin;$env:PATH"' }
          - { os: macos-latest,   cache: 'sccache', shell_prepare: '' }
          - { os: ubuntu-latest,  cache: 'ccache',  shell_prepare: '' }

    steps:
      - name: Get QtBuildScript
        run: |
          git clone --verbose https://github.com/moodyhunter/QtBuildScript

      - name: Restore Caches
        uses: actions/cache@v3
        with:
          path: ./QtBuildScript/.*cache/
          key: ${{ runner.os }}-qt-cache

      - name: Setup Windows Environment
        if: runner.os == 'Windows'     
        uses: MinoruSekine/setup-scoop@main
        with:
          add_extras_bucket: true
 
      - name: Install Packages - Windows
        if: runner.os == 'Windows'
        run: |
          scoop install msys2 cmake ninja sccache
          msys2

      - name: Process Installed Packages - Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          ${{ matrix.config.shell_prepare }}
          pacman -Sy fish

      - name: Install Packages - Linux
        if: runner.os == 'Linux'
        run: |
          export DISTRO=$(lsb_release -sc)
          echo "deb http://archive.ubuntu.com/ubuntu/ $DISTRO main universe" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://archive.ubuntu.com/ubuntu/ $DISTRO main universe" | sudo tee -a /etc/apt/sources.list
          sudo apt update
          # sudo apt upgrade -y
          sudo apt-get build-dep qtbase5-dev qtdeclarative5-dev qttools5-dev qttools5-dev-tools qtwayland5-dev-tools
          sudo apt-get install -y fish cmake ninja-build ccache

      - name: Install Packages - macOS
        if: runner.os == 'macOS'
        run: |
          brew install fish cmake ninja sccache

      - name: Setup kits
        shell: bash
        run: |
          cd ./QtBuildScript
          git submodule update --init
          echo '${{ matrix.config.cache }}' > .base-kits
          echo 'shared' >> .base-kits
          echo 'release' >> .base-kits
          echo 'tests' >> .base-kits
          echo 'examples' >> .base-kits

      - name: Update Qt
        run: |
          cd ./QtBuildScript
          ${{ matrix.config.shell_prepare }}
          fish ./update-qt.fish
