name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prepare:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, setup: 'scoop install mysys2 ninja sccache' }
          - { os: macos-latest, setup: 'brew install fish ninja' }
          - { os: ubuntu-latest }
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Get QtBuildScript
        run: |
          cd ~/
          git clone --verbose https://github.com/moodyhunter/QtBuildScript

      - name: Restore Caches
        uses: actions/cache@v3
        with:
          path: ~/QtBuildScript/.build-cache/
          key: ${{ runner.os }}-qt-cache

      # See https://github.com/ScoopInstaller/Install#for-admin
      - name: Setup Windows Environment
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"

      - name: nice
        shell: bash
        run: |
          cd ~/QtBuildScript
          echo 'sccache' > .base-kits
          echo 'shared' >> .base-kits
          echo 'release' >> .base-kits
          echo 'tests' >> .base-kits
          echo 'examples' >> .base-kits
          ${{ matrix.config.setup }}
