name: Test

on:
  workflow_dispatch:

jobs:
  prepare:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: nice
      run: echo "Nice"
